"""initial schema

Revision ID: 8d88fac9b4e6
Revises: 
Create Date: 2026-08-17 02:45:56.253284
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.core.textutil import FOLD_SQL_FUNCTION
from sqlalchemy.dialects import postgresql

revision = '8d88fac9b4e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ---- extensions + helper functions --------------------------------------------------
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gin")
    op.execute(FOLD_SQL_FUNCTION)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribute_schemas',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attribute_schemas'))
    )
    op.create_index(op.f('ix_attribute_schemas_company_id'), 'attribute_schemas', ['company_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=10), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('pk_audit_log')),
    postgresql_partition_by='RANGE (created_at)'
    )
    op.create_index('ix_audit_log_company_created', 'audit_log', ['company_id', 'created_at'], unique=False)
    op.create_index('ix_audit_log_entity', 'audit_log', ['entity', 'entity_id'], unique=False)
    op.create_table('branches',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('order_seq', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches'))
    )
    op.create_index(op.f('ix_branches_company_id'), 'branches', ['company_id'], unique=False)
    op.create_index('uq_branches_company_code_alive', 'branches', ['company_id', 'code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('categories',
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=True),
    sa.Column('icon', sa.String(length=60), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('workflow', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_index(op.f('ix_categories_company_id'), 'categories', ['company_id'], unique=False)
    op.create_index('ix_categories_company_order', 'categories', ['company_id', 'order'], unique=False)
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_table('companies',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=300), nullable=True),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('locale', sa.String(length=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sms_provider', sa.String(length=20), nullable=False),
    sa.Column('sms_api_key_enc', sa.Text(), nullable=True),
    sa.Column('sms_api_key_masked', sa.String(length=80), nullable=True),
    sa.Column('sms_default_priority', sa.String(length=20), nullable=False),
    sa.Column('sms_sender_note', sa.String(length=200), nullable=True),
    sa.Column('telegram_bot_token_enc', sa.Text(), nullable=True),
    sa.Column('telegram_bot_username', sa.String(length=80), nullable=True),
    sa.Column('telegram_bot_token_masked', sa.String(length=80), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    op.create_index('uq_companies_slug_alive', 'companies', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('notifications',
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('read_by', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_company_created', 'notifications', ['company_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_company_id'), 'notifications', ['company_id'], unique=False)
    op.create_index(op.f('ix_notifications_employee_id'), 'notifications', ['employee_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('service_type_id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=300), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('category_name', sa.String(length=200), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('final_price', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('schema_id', sa.UUID(), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=True),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('technician_id', sa.UUID(), nullable=True),
    sa.Column('technician_name', sa.String(length=200), nullable=True),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('doctor_name', sa.String(length=200), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('lab_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_index('ix_order_items_company_branch_created', 'order_items', ['company_id', 'branch_id', 'created_at'], unique=False)
    op.create_index('ix_order_items_company_category_status', 'order_items', ['company_id', 'category_id', 'status'], unique=False)
    op.create_index(op.f('ix_order_items_company_id'), 'order_items', ['company_id'], unique=False)
    op.create_index('ix_order_items_company_status_created', 'order_items', ['company_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index('ix_order_items_service_type', 'order_items', ['service_type_id', 'created_at'], unique=False)
    op.create_table('orders',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=24), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('patient_name', sa.String(length=200), nullable=False),
    sa.Column('patient_phone', sa.String(length=20), nullable=False),
    sa.Column('created_by_employee_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('payment', sa.String(length=10), nullable=False),
    sa.Column('subtotal', sa.BigInteger(), nullable=False),
    sa.Column('discount_percent', sa.SmallInteger(), nullable=False),
    sa.Column('discount_amount', sa.BigInteger(), nullable=False),
    sa.Column('total', sa.BigInteger(), nullable=False),
    sa.Column('paid_amount', sa.BigInteger(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('progress', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index('ix_orders_company_branch_created', 'orders', ['company_id', 'branch_id', 'created_at'], unique=False)
    op.create_index('ix_orders_company_created', 'orders', ['company_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_orders_company_id'), 'orders', ['company_id'], unique=False)
    op.create_index('ix_orders_company_status', 'orders', ['company_id', 'status'], unique=False)
    op.create_index('ix_orders_patient_created', 'orders', ['patient_id', 'created_at'], unique=False)
    op.create_index('uq_orders_company_number', 'orders', ['company_id', 'number'], unique=True)
    op.create_table('otp_challenges',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.Column('max_attempts', sa.SmallInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_challenges'))
    )
    op.create_index(op.f('ix_otp_challenges_phone'), 'otp_challenges', ['phone'], unique=False)
    op.create_table('outbox_messages',
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('to', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('leased_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_message_id', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_messages'))
    )
    op.create_index('ix_outbox_company_created', 'outbox_messages', ['company_id', 'created_at'], unique=False)
    op.create_index('ix_outbox_company_status_created', 'outbox_messages', ['company_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_outbox_messages_company_id'), 'outbox_messages', ['company_id'], unique=False)
    op.create_index(op.f('ix_outbox_messages_order_id'), 'outbox_messages', ['order_id'], unique=False)
    op.create_index(op.f('ix_outbox_messages_patient_id'), 'outbox_messages', ['patient_id'], unique=False)
    op.create_index('ix_outbox_queue', 'outbox_messages', ['next_attempt_at'], unique=False, postgresql_where=sa.text("status IN ('queued','scheduled') AND deleted_at IS NULL"))
    op.create_table('patients',
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('phone_extra', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=6), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('passport_number', sa.String(length=20), nullable=True),
    sa.Column('pinfl', sa.String(length=14), nullable=True),
    sa.Column('region_id', sa.UUID(), nullable=True),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('street', sa.String(length=300), nullable=True),
    sa.Column('workplace', sa.String(length=200), nullable=True),
    sa.Column('discount_percent', sa.SmallInteger(), nullable=False),
    sa.Column('contract_number', sa.String(length=60), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('stats_orders', sa.Integer(), nullable=False),
    sa.Column('stats_last_visit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stats_total_spent', sa.BigInteger(), nullable=False),
    sa.Column('portal_linked', sa.Boolean(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=32), nullable=True),
    sa.Column('portal_last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients'))
    )
    op.create_index('ix_patients_company_created', 'patients', ['company_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_patients_company_id'), 'patients', ['company_id'], unique=False)
    op.create_index('ix_patients_company_phone', 'patients', ['company_id', 'phone'], unique=False)
    op.create_index('ix_patients_telegram_chat', 'patients', ['telegram_chat_id'], unique=False)
    op.create_index('uq_patients_company_passport_alive', 'patients', ['company_id', 'passport_number'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND passport_number IS NOT NULL'))
    op.create_index('uq_patients_company_phone_noid_alive', 'patients', ['company_id', 'phone'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND passport_number IS NULL AND pinfl IS NULL'))
    op.create_index('uq_patients_company_pinfl_alive', 'patients', ['company_id', 'pinfl'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND pinfl IS NOT NULL'))
    op.create_table('payments',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('method', sa.String(length=12), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refund_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index('ix_payments_company_created', 'payments', ['company_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_payments_company_id'), 'payments', ['company_id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_table('regions',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regions'))
    )
    op.create_table('result_documents',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=True),
    sa.Column('order_item_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('pdf_file_id', sa.UUID(), nullable=True),
    sa.Column('deliveries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('public_token', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_result_documents'))
    )
    op.create_index('ix_result_documents_company_created', 'result_documents', ['company_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_result_documents_company_id'), 'result_documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_result_documents_order_id'), 'result_documents', ['order_id'], unique=False)
    op.create_index(op.f('ix_result_documents_order_item_id'), 'result_documents', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_result_documents_patient_id'), 'result_documents', ['patient_id'], unique=False)
    op.create_index(op.f('ix_result_documents_public_token'), 'result_documents', ['public_token'], unique=False)
    op.create_table('result_templates',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('service_type_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('category_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('doc', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('usage', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_result_templates'))
    )
    op.create_index(op.f('ix_result_templates_company_id'), 'result_templates', ['company_id'], unique=False)
    op.create_index('ix_result_templates_company_status', 'result_templates', ['company_id', 'status'], unique=False)
    op.create_index('ix_result_templates_service_type_ids', 'result_templates', ['service_type_ids'], unique=False, postgresql_using='gin')
    op.create_table('roles',
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', postgresql.ARRAY(sa.String(length=80)), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_company_id'), 'roles', ['company_id'], unique=False)
    op.create_index('uq_roles_company_key_alive', 'roles', ['company_id', 'key'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('service_types',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('branch_prices', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('turnaround_days', sa.SmallInteger(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('schema_id', sa.UUID(), nullable=True),
    sa.Column('document_scope', sa.String(length=10), nullable=False),
    sa.Column('default_template_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_types'))
    )
    op.create_index(op.f('ix_service_types_category_id'), 'service_types', ['category_id'], unique=False)
    op.create_index('ix_service_types_company_category', 'service_types', ['company_id', 'category_id'], unique=False)
    op.create_index(op.f('ix_service_types_company_id'), 'service_types', ['company_id'], unique=False)
    op.create_index(op.f('ix_service_types_schema_id'), 'service_types', ['schema_id'], unique=False)
    op.create_index('uq_service_types_company_code_alive', 'service_types', ['company_id', sa.literal_column('lower(code)')], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND code IS NOT NULL'))
    op.create_table('sessions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('actor', sa.String(length=10), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_subject_id'), 'sessions', ['subject_id'], unique=False)
    op.create_table('stored_files',
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stored_files'))
    )
    op.create_index(op.f('ix_stored_files_company_id'), 'stored_files', ['company_id'], unique=False)
    op.create_index('ix_stored_files_company_sha', 'stored_files', ['company_id', 'sha256'], unique=False)
    op.create_table('telegram_chat_prefs',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.String(length=32), nullable=False),
    sa.Column('lang', sa.String(length=4), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('company_id', 'chat_id', name=op.f('pk_telegram_chat_prefs'))
    )
    op.create_table('telegram_links',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.String(length=32), nullable=False),
    sa.Column('lang', sa.String(length=4), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('unlinked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_links'))
    )
    op.create_index(op.f('ix_telegram_links_chat_id'), 'telegram_links', ['chat_id'], unique=False)
    op.create_index(op.f('ix_telegram_links_company_id'), 'telegram_links', ['company_id'], unique=False)
    op.create_index(op.f('ix_telegram_links_patient_id'), 'telegram_links', ['patient_id'], unique=False)
    op.create_table('template_assets',
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('width', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('height', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template_assets'))
    )
    op.create_index(op.f('ix_template_assets_company_id'), 'template_assets', ['company_id'], unique=False)
    op.create_table('districts',
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_districts_region_id_regions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_districts'))
    )
    op.create_index(op.f('ix_districts_region_id'), 'districts', ['region_id'], unique=False)
    op.create_table('employees',
    sa.Column('branch_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('login', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('category_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('avatar_hue', sa.SmallInteger(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_logins', sa.SmallInteger(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signature_asset_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_employees_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees'))
    )
    op.create_index(op.f('ix_employees_company_id'), 'employees', ['company_id'], unique=False)
    op.create_index('ix_employees_company_status', 'employees', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_employees_role_id'), 'employees', ['role_id'], unique=False)
    op.create_index('uq_employees_login_alive', 'employees', [sa.literal_column('lower(login)')], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


    # ---- audit_log partitions (monthly RANGE) + helper to create future partitions -------
    op.execute("""
    CREATE OR REPLACE FUNCTION ensure_audit_partitions(months_ahead int DEFAULT 2) RETURNS void
    LANGUAGE plpgsql AS $$
    DECLARE m date; part text; nxt date;
    BEGIN
      FOR i IN -1..months_ahead LOOP
        m := date_trunc('month', now() + (i || ' month')::interval)::date;
        nxt := (m + interval '1 month')::date;
        part := format('audit_log_%s', to_char(m, 'YYYYMM'));
        IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = part) THEN
          EXECUTE format('CREATE TABLE %I PARTITION OF audit_log FOR VALUES FROM (%L) TO (%L)', part, m, nxt);
        END IF;
      END LOOP;
      IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'audit_log_default') THEN
        EXECUTE 'CREATE TABLE audit_log_default PARTITION OF audit_log DEFAULT';
      END IF;
    END $$;
    """)
    op.execute("SELECT ensure_audit_partitions(3)")

    # ---- search indexes (trigram over the same fold() the frontend uses) ------------------
    op.execute("CREATE INDEX ix_patients_fold_name_trgm ON patients USING gin (fold_text(full_name) gin_trgm_ops)")
    op.execute("CREATE INDEX ix_patients_phone_trgm ON patients USING gin (phone gin_trgm_ops)")
    op.execute("CREATE INDEX ix_patients_passport_trgm ON patients USING gin (fold_text(coalesce(passport_number,'')) gin_trgm_ops)")
    op.execute("CREATE INDEX ix_orders_fold_patient_trgm ON orders USING gin (fold_text(patient_name) gin_trgm_ops)")
    op.execute("CREATE INDEX ix_orders_number_lower ON orders (lower(number) text_pattern_ops)")
    op.execute("CREATE INDEX ix_order_items_fold_service_trgm ON order_items USING gin (fold_text(service_name) gin_trgm_ops)")
    op.execute("CREATE INDEX ix_outbox_fold_text_trgm ON outbox_messages USING gin (fold_text(text) gin_trgm_ops)")
    op.execute("CREATE INDEX ix_employees_fold_name_trgm ON employees USING gin (fold_text(full_name) gin_trgm_ops)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_employees_login_alive', table_name='employees', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_employees_role_id'), table_name='employees')
    op.drop_index('ix_employees_company_status', table_name='employees')
    op.drop_index(op.f('ix_employees_company_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_districts_region_id'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_template_assets_company_id'), table_name='template_assets')
    op.drop_table('template_assets')
    op.drop_index(op.f('ix_telegram_links_patient_id'), table_name='telegram_links')
    op.drop_index(op.f('ix_telegram_links_company_id'), table_name='telegram_links')
    op.drop_index(op.f('ix_telegram_links_chat_id'), table_name='telegram_links')
    op.drop_table('telegram_links')
    op.drop_table('telegram_chat_prefs')
    op.drop_index('ix_stored_files_company_sha', table_name='stored_files')
    op.drop_index(op.f('ix_stored_files_company_id'), table_name='stored_files')
    op.drop_table('stored_files')
    op.drop_index(op.f('ix_sessions_subject_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('uq_service_types_company_code_alive', table_name='service_types', postgresql_where=sa.text('deleted_at IS NULL AND code IS NOT NULL'))
    op.drop_index(op.f('ix_service_types_schema_id'), table_name='service_types')
    op.drop_index(op.f('ix_service_types_company_id'), table_name='service_types')
    op.drop_index('ix_service_types_company_category', table_name='service_types')
    op.drop_index(op.f('ix_service_types_category_id'), table_name='service_types')
    op.drop_table('service_types')
    op.drop_index('uq_roles_company_key_alive', table_name='roles', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_roles_company_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_result_templates_service_type_ids', table_name='result_templates', postgresql_using='gin')
    op.drop_index('ix_result_templates_company_status', table_name='result_templates')
    op.drop_index(op.f('ix_result_templates_company_id'), table_name='result_templates')
    op.drop_table('result_templates')
    op.drop_index(op.f('ix_result_documents_public_token'), table_name='result_documents')
    op.drop_index(op.f('ix_result_documents_patient_id'), table_name='result_documents')
    op.drop_index(op.f('ix_result_documents_order_item_id'), table_name='result_documents')
    op.drop_index(op.f('ix_result_documents_order_id'), table_name='result_documents')
    op.drop_index(op.f('ix_result_documents_company_id'), table_name='result_documents')
    op.drop_index('ix_result_documents_company_created', table_name='result_documents')
    op.drop_table('result_documents')
    op.drop_table('regions')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_company_id'), table_name='payments')
    op.drop_index('ix_payments_company_created', table_name='payments')
    op.drop_table('payments')
    op.drop_index('uq_patients_company_pinfl_alive', table_name='patients', postgresql_where=sa.text('deleted_at IS NULL AND pinfl IS NOT NULL'))
    op.drop_index('uq_patients_company_phone_noid_alive', table_name='patients', postgresql_where=sa.text('deleted_at IS NULL AND passport_number IS NULL AND pinfl IS NULL'))
    op.drop_index('uq_patients_company_passport_alive', table_name='patients', postgresql_where=sa.text('deleted_at IS NULL AND passport_number IS NOT NULL'))
    op.drop_index('ix_patients_telegram_chat', table_name='patients')
    op.drop_index('ix_patients_company_phone', table_name='patients')
    op.drop_index(op.f('ix_patients_company_id'), table_name='patients')
    op.drop_index('ix_patients_company_created', table_name='patients')
    op.drop_table('patients')
    op.drop_index('ix_outbox_queue', table_name='outbox_messages', postgresql_where=sa.text("status IN ('queued','scheduled') AND deleted_at IS NULL"))
    op.drop_index(op.f('ix_outbox_messages_patient_id'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_order_id'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_company_id'), table_name='outbox_messages')
    op.drop_index('ix_outbox_company_status_created', table_name='outbox_messages')
    op.drop_index('ix_outbox_company_created', table_name='outbox_messages')
    op.drop_table('outbox_messages')
    op.drop_index(op.f('ix_otp_challenges_phone'), table_name='otp_challenges')
    op.drop_table('otp_challenges')
    op.drop_index('uq_orders_company_number', table_name='orders')
    op.drop_index('ix_orders_patient_created', table_name='orders')
    op.drop_index('ix_orders_company_status', table_name='orders')
    op.drop_index(op.f('ix_orders_company_id'), table_name='orders')
    op.drop_index('ix_orders_company_created', table_name='orders')
    op.drop_index('ix_orders_company_branch_created', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_order_items_service_type', table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index('ix_order_items_company_status_created', table_name='order_items')
    op.drop_index(op.f('ix_order_items_company_id'), table_name='order_items')
    op.drop_index('ix_order_items_company_category_status', table_name='order_items')
    op.drop_index('ix_order_items_company_branch_created', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_notifications_employee_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_company_id'), table_name='notifications')
    op.drop_index('ix_notifications_company_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('uq_companies_slug_alive', table_name='companies', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('companies')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_index('ix_categories_company_order', table_name='categories')
    op.drop_index(op.f('ix_categories_company_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index('uq_branches_company_code_alive', table_name='branches', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_branches_company_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    op.drop_index('ix_audit_log_company_created', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_attribute_schemas_company_id'), table_name='attribute_schemas')
    op.drop_table('attribute_schemas')
    # ### end Alembic commands ###
    op.execute('DROP FUNCTION IF EXISTS ensure_audit_partitions(int)')
    op.execute('DROP FUNCTION IF EXISTS fold_text(text)')
